name: v02
description: Hero management application - version 1
version: 1.0.0

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7
  sqlite3: ^2.4.3
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
